- name: copying bootstrap file
  copy:
    src: installer/bootstrap_4.18.05.sh
    dest: /tmp/bootstrap_4.18.05.sh
    owner: admina
    group: admina
    mode: 0755

- name: copying license file
  copy:
    src: installer/license.txt
    dest: /tmp/license.txt
    owner: admina
    group: admina
    mode: 0755



# Put SELinux in permissive mode, logging actions that would be blocked.
- name: change selinux settings to permissive mode
  become: true
  selinux:
    policy: targeted
    state: permissive


#- name: copying rpm files
#  copy:
#    src: rpms
#    dest: /tmp/
#    owner: admina
#    group: admina
#    mode: 0644

- name: install java rpm from a local file
  become: true
  yum:
    name: java-1.8.0-openjdk
    state: present


- name: Check if apigee-service is already installed
  yum:
    list: apigee-service
  register: yum_list

- name: Install apigee service
  become: true
  shell: "/tmp/bootstrap_4.18.05.sh apigeeuser=luminor apigeepassword={{ apigee_password }} >> /var/log/apigee-installation-log.txt 2>&1"
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0



- name: Install apigee-setup module
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-setup install"
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0


- name: Check if apigee-provision is already installed
  yum:
    list: apigee-provision
  register: yum_list3


- name: Install apigee-provision module
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision install"
  when: yum_list3.results | selectattr("yumstate", "match", "installed") | list | length == 0
