- name: include common installations
  include_tasks: common.yaml


- name: copying apigee config from template
  become: true
  template: src=apigeeConfigFile-1node dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664


- name: Check if edge-management-server is already installed
  yum:
    list: edge-management-server
  register: yum_list2


- name: Install apigee server with {{ component }} components
  become: true
  shell: "/opt/apigee/apigee-setup/bin/setup.sh -p {{ component }} -f /opt/apigee/installConfig"
  when: yum_list2.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: open management server port in firewall
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true

- name: open edge ui port in firewall
  become: true
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true


- name: copying organization config from template
  become: true
  template: src=orgConfigFile-1node dest=/opt/apigee/orgConfig owner=apigee group=apigee mode=0664


- name: Provision new organization
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision setup-org -f /opt/apigee/orgConfig"
