- name: include common installations
  include_tasks: common.yaml


- name: copying apigee config from template (not LDAP)
  become: true
  template: src=apigeeConfigFile-13node-common dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component != "ld"


- name: copying apigee config from template (LDAP)
  become: true
  template: src=apigeeConfigFile-13node-ldap dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component == "ld"


- name: Install apigee server with {{ component }} components
  become: true
  shell: "/opt/apigee/apigee-setup/bin/setup.sh -p {{ component }} -f /opt/apigee/installConfig"

- name: open management server port in firewall
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true

- name: open edge ui port in firewall
  become: true
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true

