- name: open management server port in firewall
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ms"

- name: open edge ui port in firewall
  become: true
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ms"

- name: open postgresql 5432 port in firewall
  become: true
  firewalld:
    port: 5432/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ps"

- name: open router test port 59001 in firewall
  become: true
  firewalld:
    port: 59001/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"


- name: copying apigee config from template (not LDAP)
  become: true
  template: src=apigeeConfigFile-13node-common dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component != "ld" and component != "ms" 


- name: copying apigee config from template (MS node1)
  become: true
  template: src=apigeeConfigFile-13node-common-ms1 dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component == "ms" and node1


- name: copying apigee config from template (MS node2)
  become: true
  template: src=apigeeConfigFile-13node-common-ms2 dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component == "ms" and node2


- name: copying apigee config from template (LDAP)
  become: true
  template: src=apigeeConfigFile-13node-ldap dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664
  when: component == "ld"


- name: Install apigee server with {{ component }} components
  become: true
  shell: "/opt/apigee/apigee-setup/bin/setup.sh -p {{ component }} -f /opt/apigee/installConfig"


- name: open zookeeper port 2181 in firewall
  become: true
  firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"

- name: open zookeeper port 2888 in firewall
  become: true
  firewalld:
    port: 2888/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"


- name: open zookeeper port 3888 in firewall
  become: true
  firewalld:
    port: 3888/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"


- name: open cassandra port 9160 in firewall
  become: true
  firewalld:
    port: 9160/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"


- name: open cassandra port 7199 in firewall
  become: true
  firewalld:
    port: 7199/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"



- name: open cassandra port 9042 in firewall
  become: true
  firewalld:
    port: 9042/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"

- name: open cassandra port 7000 in firewall
  become: true
  firewalld:
    port: 7000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ds"


- name: open ldap in firewall
  become: true
  firewalld:
    port: 10389/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "ld"


- name: open router port 9001 in firewall
  become: true
  firewalld:
    port: 9001/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"

- name: open router port 4527 in firewall
  become: true
  firewalld:
    port: 4527/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"


- name: open router port 4528 in firewall
  become: true
  firewalld:
    port: 4528/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"

- name: open router port 8082 in firewall
  become: true
  firewalld:
    port: 8082/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"

- name: open router port 8081 in firewall
  become: true
  firewalld:
    port: 8081/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: component == "rmp"

