- name: copying rpm files
  copy:
    src: installer/bootstrap_4.18.05.sh
    dest: /tmp/bootstrap_4.18.05.sh
    owner: admina
    group: admina
    mode: 0755

- name: copying rpm files
  copy:
    src: installer/license.txt
    dest: /tmp/license.txt
    owner: admina
    group: admina
    mode: 0755



# Put SELinux in permissive mode, logging actions that would be blocked.
- name: change selinux settings to permissive mode
  become: true
  selinux:
    policy: targeted
    state: permissive

- name: copying rpm files
  copy:
    src: rpms
    dest: /tmp/
    owner: admina
    group: admina
    mode: 0644

- name: install java rpm from a local file
  become: true
  yum:
    name: /tmp/rpms/jdk-8u181-linux-x64.rpm
    state: present


- name: Check if apigee-service is already installed
  yum:
    list: apigee-service
  register: yum_list

- name: Install apigee service
  become: true
  shell: "/tmp/bootstrap_4.18.05.sh apigeeuser=luminor apigeepassword={{ apigee_password }} >> /var/log/apigee-installation-log.txt 2>&1"
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0



- name: Install apigee setup
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-setup install"
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0


- name: copying apigee config from template
  become: true
  template: src=apigeeConfigFile-1node dest=/opt/apigee/installConfig owner=apigee group=apigee mode=0664


- name: Check if edge-management-server is already installed
  yum:
    list: edge-management-server
  register: yum_list2


- name: Install apigee server with {{ component }} components
  become: true
  shell: "/opt/apigee/apigee-setup/bin/setup.sh -p {{ component }} -f /opt/apigee/installConfig"
  when: yum_list2.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: open management server port in firewall
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true

- name: open edge ui port in firewall
  become: true
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true


- name: Check if apigee-provision is already installed
  yum:
    list: apigee-provision
  register: yum_list3


- name: Install provisioning service
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision install"
  when: (yum_list2.results | selectattr("yumstate", "match", "installed") | list | length > 0) and
        (yum_list3.results | selectattr("yumstate", "match", "installed") | list | length == 0)


- name: copying organization config from template
  become: true
  template: src=orgConfigFile-1node dest=/opt/apigee/orgConfig owner=apigee group=apigee mode=0664


- name: Provision new organization
  become: true
  shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision setup-org -f /opt/apigee/orgConfig"
